server:
  port: ${SERVER_PORT:8085}
spring:
  datasource:
    url: jdbc:h2:mem:weather
    username: vg
    password: vgDemo
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
okta:
  oauth2:
    issuer: <<Auth0 Issuer>>
    client-id: <<Auth0 Client Id>>
    client-secret: <<Auth0 Client Secret>>
open-weather-map:
  api-key: <<Open Weather Map API Key>>
logging:
  level:
    org.springframework.security.web: INFO
